# Generated by Django 5.0.7 on 2024-08-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
