# Generated by Django 5.0.7 on 2024-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='given_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
